name: smile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  image: ^4.2.0
  path_provider: ^2.1.2
  get: ^4.6.6
  google_fonts: ^6.1.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  http_parser: ^4.0.2
  flutter_charts: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
